device: "cuda"
data_path: "data/tiny_nerf_data.npz"

train:
  n_iters: 1
  lr: 5e-4
  lr_decay_rate: 0.1
  lr_decay_steps: 5000
  epoch: 1000
  batch_size: 1024
  logs_dir: "logs"
  step_validation: 200

model:
  L_position: 10
  L_direction: 4
  n_neurons: 256
  activation: relu
  encoding: sinus  # options: "sinus" (default) or "gaussian"
  num_features: 256   # if gaussian
  sigma: 10           # if gaussian

render:
  near: 2.0
  far: 6.0
  n_samples: 64
  chunk_size: 4096